version: 2.1
jobs:
  dummy:
    docker:
      - image: cimg/base:2024.06

    working_directory: ~/repo
    steps:
      - run:
          name: empty
          command: echo "hi"
workflows:
  mycoolthing:
    jobs:
      - dummy

      - dummy:
          name: my-cool-deploy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
