name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          default_bump: patch
          create_annotated_tag: true
      - name: Create changelog
        run:
          git log --pretty=oneline --abbrev-commit ${{ steps.tag_version.outputs.previous_tag }}...HEAD > changelog
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          bodyFile: changelog
